package controlplane.route;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.base.MoreObjects;
import controlplane.network.Interface;
import controlplane.route.builder.BgpRouteBuilder;
import datamodel.aspath.AsPath;
import datamodel.aspath.AsPathIntf;
import datamodel.community.CommunityListIntf;
import datamodel.ipv4.Ip;
import datamodel.ipv4.Prefix;
import datamodel.path.Path;
import datamodel.route.HasAsPath;
import datamodel.route.HasCommunity;
import datamodel.route.HasCost;
import datamodel.route.HasLocalPreference;
import datamodel.route.HasOrigin;
import datamodel.route.HasWeight;
import main.Configuration;

import javax.annotation.Nonnull;
import java.util.Comparator;
import java.util.Objects;
import java.util.Set;

public class BgpRoute extends DynamicRoute<BgpRouteBuilder, BgpRoute>
    implements HasLocalPreference, HasAsPath, HasCommunity, HasWeight, HasCost, HasOrigin {

  private static final String PROP_WEIGHT = "weight";
  private static final String PROP_LOCAL_PREFERENCE = "localPreference";
  private static final String PROP_AS_PATH = "asPath";
  private static final String PROP_MED = "med";
  private static final String PROP_ORIGIN_TYPE = "originType";
  private static final String PROP_COMMUNITIES = "communities";
  private static final String PROP_BGP_ROUTE_TYPE = "bgpRouteType";
  private static final String PROP_IGP_COST_TO_NEXTHOP = "igpCostToNextHop";
  private static final String PROP_SUPPRESSED = "suppressed";

  public enum OriginType {
    /**
     * Network Layer Reachability Information (NLRI) is interior to the originating AS. <br>
     * The Origin attribute of the routes imported into a BGP routing table using the network
     * command is IGP.
     */
    IGP,
    /** Network Layer Reachability Information (NLRI) learned via the EGP protocol. */
    EGP,
    /**
     * Network Layer Reachability Information (NLRI) learned by some other means. <br>
     * For example, the Origin attribute of the routes imported by BGP using the import-route
     * command is Incomplete.
     */
    INCOMPLETE
  }

  public enum BgpRouteType {
    AGGREGATE,
    SUMMARY,
    NETWORK,
    IMPORT,
    FROM_EBGP_NEIGHBOR,
    FROM_IBGP_NEIGHBOR,
    FROM_ROUTE_REFLECTOR,
    FROM_CLIENT
  }

  int _weight;
  int _localPreference;
  AsPathIntf _asPath;
  /**
   * For huawei devices, cost means med for BGP routes. <a
   * href="https://support.huawei.com/enterprise/en/doc/EDOC1100197672/f4783539/apply-cost">huawei-doc</a>
   */
  long _med;
  /**
   * The origin attribute is generated by the speaker that originates the associated information.
   * <u>Its value should not be changed by other speaker.</u> Routing policies may change this
   * field.
   */
  OriginType _origin;

  CommunityListIntf _communityList;
  BgpRouteType _bgpRouteType;
  long _igpCostToNextHop;

  boolean _suppressed;

  public BgpRoute(
      Set<Prefix> prefixes,
      int prefixesBdd,
      Ip nextHopIp,
      Interface nextHopInterface,
      int preference,
      int admin,
      long tag,
      Path path,
      int weight,
      int localPreference,
      AsPathIntf asPath,
      long med,
      OriginType origin,
      CommunityListIntf communityList,
      BgpRouteType bgpRouteType,
      long igpCostToNextHop,
      boolean suppressed) {
    super(prefixes, prefixesBdd, nextHopIp, nextHopInterface, preference, admin, tag, path);
    _weight = weight;
    _localPreference = localPreference;
    _asPath = asPath;
    _med = med;
    _origin = origin;
    _communityList = communityList;
    _bgpRouteType = bgpRouteType;
    _igpCostToNextHop = igpCostToNextHop;
    _suppressed = suppressed;
  }

  @Override
  public RoutingProtocol getRoutingProtocol() {
    return RoutingProtocol.BGP;
  }

  /* weight = preferred value*/
  @Override
  @JsonProperty(PROP_WEIGHT)
  public int getWeight() {
    return _weight;
  }

  @Override
  @JsonProperty(PROP_WEIGHT)
  public void setWeight(int weight) {
    _weight = weight;
  }

  @JsonProperty(PROP_LOCAL_PREFERENCE)
  public int getLocalPreference() {
    return _localPreference;
  }

  @JsonProperty(PROP_LOCAL_PREFERENCE)
  public void setLocalPreference(int lp) {
    _localPreference = lp;
  }

  @Override
  @JsonProperty(PROP_AS_PATH)
  public AsPathIntf getAsPath() {
    return _asPath;
  }

  @Override
  @JsonProperty(PROP_AS_PATH)
  public void setAsPath(AsPathIntf asPath) {
    _asPath = asPath;
  }

  /* metric = cost = med */
  @JsonProperty(PROP_MED)
  public void setMed(long med) {
    _med = med;
  }

  @JsonProperty(PROP_MED)
  public long getMed() {
    return _med;
  }

  @Override
  public long getMetric() {
    return getMed();
  }

  @Override
  @JsonIgnore
  public long getCost() {
    return getMed();
  }

  @Override
  @JsonIgnore
  public void setCost(long cost) {
    setMed(cost);
  }

  @Override
  @JsonProperty(PROP_ORIGIN_TYPE)
  public OriginType getOrigin() {
    return _origin;
  }

  @Override
  @JsonProperty(PROP_ORIGIN_TYPE)
  public void setOrigin(OriginType origin) {
    _origin = origin;
  }

  @JsonProperty(PROP_COMMUNITIES)
  public CommunityListIntf getCommunities() {
    return _communityList;
  }

  @Override
  public void setCommunities(CommunityListIntf communities) {
    _communityList = communities;
  }

  @JsonProperty(PROP_BGP_ROUTE_TYPE)
  public BgpRouteType getType() {
    return _bgpRouteType;
  }

  @JsonProperty(PROP_BGP_ROUTE_TYPE)
  public void setType(BgpRouteType bgpRouteType) {
    _bgpRouteType = bgpRouteType;
  }

  @JsonProperty(PROP_IGP_COST_TO_NEXTHOP)
  public long getIgpCostToNextHop() {
    return _igpCostToNextHop;
  }

  @JsonProperty(PROP_IGP_COST_TO_NEXTHOP)
  public void setIgpCostToNextHop(long igpCostToNextHop) {
    _igpCostToNextHop = igpCostToNextHop;
  }

  @JsonProperty(PROP_SUPPRESSED)
  public boolean isSuppressed() {
    return _suppressed;
  }

  @JsonProperty(PROP_SUPPRESSED)
  public void setSuppressed(boolean suppressed) {
    _suppressed = suppressed;
  }

  /**
   * @return a copy of this route with the igp cost to next hop set to default value (see {@link
   *     Attributes#BGP_ROUTE_DEFAULT_IGP_COST_TO_NEXT_HOP}).
   */
  public BgpRoute prepareOut() {
    return toBuilder()
        .setIgpCostToNextHop(Attributes.BGP_ROUTE_DEFAULT_IGP_COST_TO_NEXT_HOP)
        .build();
  }

  @Override
  public int compareTo(@Nonnull Route o) {
    if (o instanceof BgpRoute) {
      return Comparator
          // compare weight, prefer bigger value
          .comparing(BgpRoute::getWeight, Comparator.reverseOrder())
          // compare local preference, prefer bigger value
          .thenComparing(BgpRoute::getLocalPreference, Comparator.reverseOrder())
          // how we learn this route? aggregate? summary? network? import? from peer?
          .thenComparing(
              r -> Configuration.DEFAULT_VENDOR.getSourcePreference(r._bgpRouteType),
              Comparator.reverseOrder())
          // compare as path, prefer shorter path
          .thenComparing(r -> r._asPath.length())
          // compare origin type, prefer IGP(i) over EGP(e) over INCOMPLETE(?)
          .thenComparing(r -> r._origin.ordinal())
          // compare multi-exit discriminator (MED), prefer smaller value
          .thenComparing(r -> r._med)
          // prefer route from EBGP peers to route from IBGP peers
          .thenComparing(
              r -> Configuration.DEFAULT_VENDOR.getPeerPreference(r._bgpRouteType),
              Comparator.reverseOrder())
          // compare igp cost to next hop ip, prefer smaller value
          .thenComparing(BgpRoute::getIgpCostToNextHop)
          .compare(this, (BgpRoute) o);
    } else {
      return super.compareTo(o);
    }
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (!(o instanceof BgpRoute)) {
      return false;
    }
    BgpRoute other = (BgpRoute) o;
    return _prefixesBdd == other._prefixesBdd
        && Objects.equals(_nextHopIp, other._nextHopIp)
        && Objects.equals(_nextHopInterface, other._nextHopInterface)
        && _preference == other._preference
        && _admin == other._admin
        && _tag == other._tag
        && Objects.equals(_path, other._path)
        && _weight == other._weight
        && _localPreference == other._localPreference
        && Objects.equals(_asPath, other._asPath)
        && _med == other._med
        && _origin == other._origin
        && Objects.equals(_communityList, other._communityList)
        && _bgpRouteType == other._bgpRouteType
        && _igpCostToNextHop == other._igpCostToNextHop
        && _suppressed == other._suppressed;
  }

  @Override
  public int hashCode() {
    int h;
    h = _prefixesBdd;
    h = h * 31 + Objects.hashCode(_nextHopIp);
    h = h * 31 + Objects.hashCode(_nextHopInterface);
    h = h * 31 + _preference;
    h = h * 31 + _admin;
    h = h * 31 + Long.hashCode(_tag);
    h = h * 31 + Objects.hashCode(_path);
    h = h * 31 + _weight;
    h = h * 31 + _localPreference;
    h = h * 31 + _asPath.hashCode();
    h = h * 31 + Long.hashCode(_med);
    h = h * 31 + _origin.ordinal();
    h = h * 31 + Objects.hashCode(_communityList);
    h = h * 31 + _bgpRouteType.ordinal();
    h = h * 31 + Long.hashCode(_igpCostToNextHop);
    h = h * 31 + Boolean.hashCode(_suppressed);
    return h;
  }

  @Override
  public BgpRouteBuilder toBuilder() {
    return new BgpRouteBuilder()
        .setPrefixes(_prefixes)
        .setPrefixesBdd(_prefixesBdd)
        .setNextHopIp(_nextHopIp)
        .setNextHopInterface(_nextHopInterface)
        .setPreference(_preference)
        .setAdmin(_admin)
        .setTag(_tag)
        .setPath(_path)
        .setWeight(_weight)
        .setLocalPreference(_localPreference)
        .setAsPath(_asPath)
        .setMetric(_med)
        .setOrigin(_origin)
        .setCommunityList(_communityList)
        .setType(_bgpRouteType)
        .setIgpCostToNextHop(_igpCostToNextHop)
        .setSuppressed(_suppressed);
  }

  /**
   * We do not have to copy the {@link AsPath} of this route since the {@link AsPath#getAsSets()}
   * returns an immutable list.
   */
  @Override
  public Attributes.Builder toAttributesBuilder() {
    return super.toAttributesBuilder()
        .setPath(_path)
        .setWeight(_weight)
        .setLocalPreference(_localPreference)
        .setAsPath(_asPath)
        .setMed(_med)
        .setOrigin(_origin)
        .setCommunityList(_communityList)
        .setBgpRouteType(_bgpRouteType)
        .setIgpCostToNextHop(_igpCostToNextHop)
        .setSuppressed(_suppressed);
  }

  @Override
  public MoreObjects.ToStringHelper toStringHelper() {
    return super.toStringHelper()
        .add("localPreference", _localPreference)
        .add("asPath", _asPath)
        .add("communities", _communityList)
        .add("igpCostToNextHop", Attributes.printIgpCostToNextHop(_igpCostToNextHop))
        .add("bgpRouteType", _bgpRouteType);
  }
}
